### ISSUE TITLE
Should we move pusher-chatkit-server to the @pusher org?

### ISSUE THREAD

**Issue by lukejacksonn** [bookercodes/build-a-chat-app-with-react-and-pusher-chatkit#1]
Predominantly used here https://github.com/bookercodes/build-a-chat-app-with-react-and-pusher-chatkit#step-3-setup-a-basic-node-sever

**Comment by bookercodes** [comment]
Yeah, I think so.

I am also in strong favour of `@pusher/chatkit-client` and `@pusher/chatkit-server`

**Comment by lukejacksonn** [comment]
Cool, I'd go ahead and republish `pusher-chatkit-server` as `@pusher/chatkit-server`first then consider renaming `@pusher/chatkit` as a seperate issue.

**Comment by bookercodes** [comment]
Something for next iteration, I think

**Comment by lukejacksonn** [comment]
How come? I can hit the button now.. https://github.com/pusher/chatkit-server-node/pull/13
