### ISSUE TITLE
Why git checkout tags/template?

### ISSUE THREAD

**Issue by lukejacksonn** [bookercodes/build-a-chat-app-with-react-and-pusher-chatkit#3]
How come you chose this approach? It puts you in an usual git place. I don't believe many people will have used this before too much. Could we get away without?

![image](https://user-images.githubusercontent.com/1457604/37963301-c7ef1e22-31b5-11e8-8d8a-b9c4d8b1ee11.png)

**Comment by bookercodes** [comment]
Yeah, this is a great point.

Possible solutions:

* Move starter template to a separate repository. `git clone` only
* Find a way to `checkout` without being in "detached HEAD" state 


Thoughts

**Comment by lukejacksonn** [comment]
Option A; alternatively have you considered `create-react-app`?

**Comment by bookercodes** [comment]
Yeah, I started the tutorial with `create-react-app` but I wanted to remove all the PWA and testing-related code. I also wanted to add a minimal server (with all the boilerplate stuff like `body-parser`) pre-installed.

**Comment by lukejacksonn** [comment]
Yeh, I know what you mean regard the PWA stuff.. so this is a personalised CRA by the looks of things. Humm 🤔 I would probably leave it as is but make the `tags/template` branch the `master` so that people don't have to do the checkout and can just commit on top of master like usual.

**Comment by lukejacksonn** [comment]
A `complete` branch has been pushed up.. but I am not sure that `master` is actually inline with the starter template. Will check again.

**Comment by bookercodes** [comment]
All sorted
